name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.3-bullseye
        env:
          POSTGRES_DB: main
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: "y7jHf&DNWG15"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.23.4
        id: go

      - name: Check out code into the Go module directory.
        uses: actions/checkout@v4

      - name: Install golang-migrate package
        run: |
          $ curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64.tar.gz /usr/bin/
          which migrate

      - name: Run Migration
        run: make migrate_up

      - name: Test
        run: make test
